### ISSUE TITLE
Highlight color doesn't work because of the quotation marks

### ISSUE THREAD

**Issue by KatiRasanen** [paazmaya/shigehachi#10]
### Expected behaviour

On the generated image the differences should be marked with the color specified in options like pink, green, red etc.

### Actual behaviour

When running shigehachi comparison with default setting and defined color: 'red' or color: '#ff0000' result remains the same as without the color option. Even the default color pink is not shown.

From the command line it can be seen shigehachi adds quotation marks around the color option. When running the same command on command line without those quotation marks, result is as expected and the wanted color is shown. Works also with hex code color codes. 

So if you agree it would be nice to remove those quotation marks :)

**Comment by paazmaya** [comment]
I agree :neckbeard:

**Comment by paazmaya** [comment]
https://www.npmjs.com/package/shigehachi

`v4.0.5` published with a possible fix.
